OPS-5193-edusharing-kubernetes-update-1-26-improvements
hpi-schul-cloud/infra-deploy pull request #39
Opened 2023-11-13 12:43 UTC by aimee-889

# Description
make playbook more robust, especially when executed locally

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-11-13 14:59 UTC, RalfNellesCap approved these changes

2023-11-13 15:28 UTC, dimapin requested changes
Please use another shortcut

2023-11-14 07:56 UTC, dimapin commented on ansible/edusharing-crawler-playbook.yml
> +    check_mode: false
Can you leave a comment about the reason for disabling the check mode and change notification here

2023-11-14 08:56 UTC, dimapin approved these changes

2023-11-14 13:02 UTC, merged